In [64]:
import pandas as pd
import numpy as np
from retinopathy.callbacks import cohen_kappa_score
from retinopathy.models.heads import regression_to_class

In [65]:
df1 = pd.read_pickle('../reg_seresnext50_rms_512_medium_mse_aptos2019_fold0_awesome_babbage_on_idrid_fold0.pkl')
df1.drop(columns=['features'], inplace=True)
df1.head()

image_id diagnosis_true  \
0  IDRiD_001      tensor(3)   
1  IDRiD_005      tensor(4)   
2  IDRiD_011      tensor(3)   
3  IDRiD_014      tensor(4)   
4  IDRiD_018      tensor(2)   

                                              logits  regression  
0  [0.013231222, 0.008637085, 0.73025614, 0.21559...    2.241249  
1  [0.10114664, 0.0289896, 0.0063282703, 0.050347...    3.493390  
2  [0.011858935, 0.015906084, 0.9036092, 0.050163...    2.058267  
3  [0.007668243, 0.006203685, 0.0047766133, 0.012...    3.860499  
4  [0.038102895, 0.09725846, 0.7801861, 0.0401610...    1.952713

In [66]:
def regression_from_logits(logits):
    return logits[1] + logits[2] * 2 + logits[3] * 3 + logits[4] * 4

df1['regression_from_logits'] = df1['logits'].apply(regression_from_logits)
df1.head()

image_id diagnosis_true  \
0  IDRiD_001      tensor(3)   
1  IDRiD_005      tensor(4)   
2  IDRiD_011      tensor(3)   
3  IDRiD_014      tensor(4)   
4  IDRiD_018      tensor(2)   

                                              logits  regression  \
0  [0.013231222, 0.008637085, 0.73025614, 0.21559...    2.241249   
1  [0.10114664, 0.0289896, 0.0063282703, 0.050347...    3.493390   
2  [0.011858935, 0.015906084, 0.9036092, 0.050163...    2.058267   
3  [0.007668243, 0.006203685, 0.0047766133, 0.012...    3.860499   
4  [0.038102895, 0.09725846, 0.7801861, 0.0401610...    1.952713   

   regression_from_logits  
0                2.245056  
1                3.445441  
2                2.047464  
3                3.928212  
4                1.955280

In [67]:
df1['diagnisos_regression'] = df1['regression'].apply(regression_to_class).apply(int)
df1['diagnisos_logits'] = df1['logits'].apply(np.argmax)
df1.head()


image_id diagnosis_true  \
0  IDRiD_001      tensor(3)   
1  IDRiD_005      tensor(4)   
2  IDRiD_011      tensor(3)   
3  IDRiD_014      tensor(4)   
4  IDRiD_018      tensor(2)   

                                              logits  regression  \
0  [0.013231222, 0.008637085, 0.73025614, 0.21559...    2.241249   
1  [0.10114664, 0.0289896, 0.0063282703, 0.050347...    3.493390   
2  [0.011858935, 0.015906084, 0.9036092, 0.050163...    2.058267   
3  [0.007668243, 0.006203685, 0.0047766133, 0.012...    3.860499   
4  [0.038102895, 0.09725846, 0.7801861, 0.0401610...    1.952713   

   regression_from_logits  diagnisos_regression  diagnisos_logits  
0                2.245056                     2                 2  
1                3.445441                     3                 4  
2                2.047464                     2                 2  
3                3.928212                     4                 4  
4                1.955280                     2                 2

In [68]:
df1['diagnosis_true'] = df1['diagnosis_true'].apply(int)

df1['diagnisos_reg_from_log'] = df1['regression_from_logits'].apply(regression_to_class).apply(int)

In [69]:
score, num, denom = cohen_kappa_score(df1['diagnosis_true'].values, 
                          df1['diagnisos_logits'].values, 
                          weights='quadratic')
print(score)

0.759223365860179


In [70]:

score, num, denom = cohen_kappa_score(df1['diagnosis_true'].values, 
                          df1['diagnisos_regression'].values, 
                          weights='quadratic')
print(score)

0.7415271254212428


In [71]:

score, num, denom = cohen_kappa_score(df1['diagnosis_true'].values, 
                          df1['diagnisos_reg_from_log'].values, 
                          weights='quadratic')
print(score)


0.7616397302793536


In [72]:
df1[df1['diagnosis_true'] != df1['diagnisos_reg_from_log']]

image_id  diagnosis_true  \
0    IDRiD_001               3   
1    IDRiD_005               4   
2    IDRiD_011               3   
6    IDRiD_024               4   
7    IDRiD_030               4   
9    IDRiD_034               3   
12   IDRiD_045               2   
13   IDRiD_046               4   
14   IDRiD_049               3   
16   IDRiD_051               2   
20   IDRiD_065               3   
22   IDRiD_074               2   
24   IDRiD_088               3   
25   IDRiD_090               4   
27   IDRiD_101               3   
29   IDRiD_110               3   
30   IDRiD_114               3   
32   IDRiD_119               4   
34   IDRiD_124               2   
37   IDRiD_137               2   
39   IDRiD_146               0   
41   IDRiD_152               0   
42   IDRiD_153               0   
46   IDRiD_166               0   
57   IDRiD_224               4   
65   IDRiD_251               0   
66   IDRiD_252               2   
67   IDRiD_253               3   
69   IDRiD_262               2   
70   IDRiD_266               1   
73   IDRiD_278               3   
75   IDRiD_282               2   
76   IDRiD_291               1   
79   IDRiD_302               1   
80   IDRiD_309               3   
91   IDRiD_345               0   
93   IDRiD_352               0   
94   IDRiD_364               3   
95   IDRiD_365               0   
97   IDRiD_372               3   
98   IDRiD_376               3   
99   IDRiD_384               3   
100  IDRiD_388               1   
101  IDRiD_392               4   
102  IDRiD_394               4   
105  IDRiD_412               2   
106  IDRiD_002               4   
107  IDRiD_008               2   
116  IDRiD_045               0   
117  IDRiD_048               4   
121  IDRiD_060               3   
122  IDRiD_061               4   
124  IDRiD_076               2   
126  IDRiD_084               2   
129  IDRiD_094               0   
130  IDRiD_097               0   

                                                logits  regression  \
0    [0.013231222, 0.008637085, 0.73025614, 0.21559...    2.241249   
1    [0.10114664, 0.0289896, 0.0063282703, 0.050347...    3.493390   
2    [0.011858935, 0.015906084, 0.9036092, 0.050163...    2.058267   
6    [0.048790153, 0.12205569, 0.3810807, 0.1345484...    2.418279   
7    [0.028467596, 0.008369564, 0.3763195, 0.205151...    3.050488   
9    [0.023887828, 0.014313844, 0.7780228, 0.163983...    2.056674   
12   [0.3135545, 0.0634013, 0.509784, 0.07251287, 0...    1.617755   
13   [0.21101043, 0.098241754, 0.64645225, 0.025946...    1.211233   
14   [0.02046901, 0.01142912, 0.8319336, 0.10941358...    2.170901   
16   [0.03714208, 0.8422897, 0.070583075, 0.0094649...    1.228551   
20   [0.14327437, 0.46193218, 0.34626442, 0.0180027...    1.160176   
22   [0.01571586, 0.5843479, 0.3389033, 0.010290413...    1.537929   
24   [0.14276186, 0.2562257, 0.5169418, 0.069241926...    1.686439   
25   [0.013981238, 0.008904123, 0.91487694, 0.05258...    2.092127   
27   [0.015787324, 0.010842741, 0.87353253, 0.08092...    2.131637   
29   [0.02130167, 0.00786723, 0.028772496, 0.287833...    3.411088   
30   [0.0040452788, 0.0030099687, 0.8804181, 0.0765...    2.547068   
32   [0.021432439, 0.0024534815, 0.010536361, 0.894...    3.288906   
34   [0.024769546, 0.9255, 0.035429306, 0.005170412...    1.099026   
37   [0.06928754, 0.51132727, 0.36832795, 0.0206915...    1.304356   
39   [0.42308944, 0.011971636, 0.007335985, 0.38802...    2.155368   
41   [0.42880386, 0.544764, 0.0031973387, 0.0086635...    0.464590   
42   [0.3071051, 0.117582984, 0.35141933, 0.1139592...    1.831347   
46   [0.3392605, 0.4720056, 0.11669564, 0.027945843...    1.121588   
57   [0.03914216, 0.0075050406, 0.3540531, 0.296483...    3.175687   
65   [0.7241927, 0.05314824, 0.17989983, 0.02062909...   -0.000570   
66   [0.6612754, 0.055302206, 0.21977913, 0.0355642...    0.346779   
67   [0.005765122, 0.013806587, 0.9675243, 0.009310...    1.843959   
69   [0.03813638, 0.92110455, 0.02786

In [73]:

import numpy as np
import pandas as pd
import os
import scipy as sp
from functools import partial
from sklearn import metrics
from collections import Counter
import json

In [74]:
class OptimizedRounder(object):
    def __init__(self):
        self.coef_ = 0

    def _kappa_loss(self, coef, X, y):
        X_p = np.copy(X)
        for i, pred in enumerate(X_p):
            if pred < coef[0]:
                X_p[i] = 0
            elif pred >= coef[0] and pred < coef[1]:
                X_p[i] = 1
            elif pred >= coef[1] and pred < coef[2]:
                X_p[i] = 2
            elif pred >= coef[2] and pred < coef[3]:
                X_p[i] = 3
            else:
                X_p[i] = 4

        ll = metrics.cohen_kappa_score(y, X_p, weights='quadratic')
        return -ll

    def fit(self, X, y):
        loss_partial = partial(self._kappa_loss, X=X, y=y)
        initial_coef = [0.5, 1.5, 2.5, 3.5]
        self.coef_ = sp.optimize.minimize(loss_partial, initial_coef, method='nelder-mead')

    def predict(self, X, coef):
        X_p = np.copy(X)
        for i, pred in enumerate(X_p):
            if pred < coef[0]:
                X_p[i] = 0
            elif pred >= coef[0] and pred < coef[1]:
                X_p[i] = 1
            elif pred >= coef[1] and pred < coef[2]:
                X_p[i] = 2
            elif pred >= coef[2] and pred < coef[3]:
                X_p[i] = 3
            else:
                X_p[i] = 4
        return X_p

    def coefficients(self):
        return self.coef_['x']

In [75]:
optR = OptimizedRounder()
optR.fit(df1['regression'], df1['diagnosis_true'])
coefficients = optR.coefficients()
print(coefficients)
df1['optimized'] = optR.predict(df1['regression'], coefficients)

score, num, denom = cohen_kappa_score(df1['diagnosis_true'].values, 
                          df1['optimized'].values, 
                          weights='quadratic')
print(score)

[0.56882927 1.59116436 2.02082512 3.03259576]
0.8005066115827089


In [76]:
optR = OptimizedRounder()
optR.fit(df1['regression_from_logits'], df1['diagnosis_true'])
coefficients = optR.coefficients()
print(coefficients)
df1['optimized'] = optR.predict(df1['regression_from_logits'], coefficients)

score, num, denom = cohen_kappa_score(df1['diagnosis_true'].values, 
                          df1['optimized'].values, 
                          weights='quadratic')
print(score)

[0.52773437 1.46015625 2.46289062 3.43164063]
0.7767686172548882


In [77]:

optR = OptimizedRounder()
optR.fit(df1['regression_from_logits'], df1['diagnosis_true'])
coefficients = optR.coefficients()
print(coefficients)
df1['optimized'] = optR.predict(df1['regression_from_logits'], coefficients)

score, num, denom = cohen_kappa_score(df1['diagnosis_true'].values, 
                          df1['optimized'].values, 
                          weights='quadratic')
print(score)


[0.52773437 1.46015625 2.46289062 3.43164063]
0.7767686172548882
